name: Build

"on":
  push:
    branches:
      - main

jobs:
  linux:
    name: linux (${{ matrix.mode }})
    runs-on: ubuntu-24.04
    container: archlinux:latest
    strategy:
      fail-fast: false
      matrix:
        mode:
          - debug
          - release
    env:
      XMAKE_ROOT: "y"
    steps:
      - name: Install dependencies
        run: >
          pacman -Syu --noconfirm base-devel git xmake clang llvm libc++ libc++abi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache xmake
        uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
            build
          key: xmake-linux-${{ matrix.mode }}-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-linux-${{ matrix.mode }}-

      - name: Configure
        run: >
          xmake f -y -m ${{ matrix.mode }}
          --toolchain=clang

      - name: Build
        run: xmake -y -v

  window:
    name: windows (${{ matrix.mode }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mode:
          - debug
          - release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Cache xmake
        uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
            build
          key: xmake-linux-${{ matrix.mode }}-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-linux-${{ matrix.mode }}-

      - name: Configure
        run: xmake f -y -m ${{ matrix.mode }}

      - name: Build
        run: xmake -y -v
